package com.hexaware.cms.service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.hexaware.cms.entity.Incident;
import com.hexaware.cms.exception.IncidentNotFoundException;
import com.hexaware.cms.repository.IncidentRepository;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

@Service
public class ReportServiceImpl implements IReportService {

	@Autowired
	private IncidentRepository incidentRepository;
	private static final Logger logger = LoggerFactory.getLogger(UserServiceImpl.class);


	@Override
	public ByteArrayInputStream generateIncidentReport(Integer incidentId) {
		

		

		Incident incident = incidentRepository.findById(incidentId)
				.orElseThrow(() -> new IncidentNotFoundException("Incident not found"));

		Document document = new Document();

		ByteArrayOutputStream out = new ByteArrayOutputStream();

		try {
			logger.info("Generating PDF for Incident {}",
			        incidentId);

			PdfWriter.getInstance(document, out);

			document.open();

			Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);

			Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 15);

			Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

			// ===========================
			// TITLE
			// ===========================

			Paragraph title = new Paragraph("CRIME MANAGEMENT SYSTEM", titleFont);

			title.setAlignment(Paragraph.ALIGN_CENTER);

			document.add(title);

			Paragraph subtitle = new Paragraph("INCIDENT REPORT", headingFont);

			subtitle.setAlignment(Paragraph.ALIGN_CENTER);

			document.add(subtitle);

			document.add(new Paragraph("=============================================================="));

			document.add(new Paragraph("Generated On : " + LocalDate.now(), normalFont));

			document.add(new Paragraph(" "));

			// ===========================
			// INCIDENT DETAILS
			// ===========================

			document.add(new Paragraph("INCIDENT DETAILS", headingFont));

			document.add(new Paragraph("--------------------------------------------------------------"));

			document.add(
					new Paragraph(String.format("%-20s : %s", "Incident ID", incident.getIncidentId()), normalFont));

			document.add(new Paragraph(
					String.format("%-20s : %s", "Incident Type", incident.getIncidentType().getIncidentTypeName()),
					normalFont));

			document.add(new Paragraph(String.format("%-20s : %s", "Title", incident.getTitle()), normalFont));

			document.add(
					new Paragraph(String.format("%-20s : %s", "Description", incident.getDescription()), normalFont));

			document.add(new Paragraph(String.format("%-20s : %s", "Location", incident.getLocation()), normalFont));

			document.add(new Paragraph(String.format("%-20s : %s", "Incident Date", incident.getIncidentDate()),
					normalFont));

			document.add(new Paragraph(" "));

			// ===========================
			// REPORTER DETAILS
			// ===========================

			document.add(new Paragraph("REPORTER DETAILS", headingFont));

			document.add(new Paragraph("--------------------------------------------------------------"));

			document.add(new Paragraph(String.format("%-20s : %s", "Name",
					incident.getUser().getFirstName() + " " + incident.getUser().getLastName()), normalFont));

			document.add(
					new Paragraph(String.format("%-20s : %s", "Email", incident.getUser().getEmail()), normalFont));

			document.add(
					new Paragraph(String.format("%-20s : %s", "Phone", incident.getUser().getPhone()), normalFont));

			document.add(new Paragraph(" "));

			// ===========================
			// STATUS
			// ===========================

			document.add(new Paragraph("INCIDENT STATUS", headingFont));

			document.add(new Paragraph("--------------------------------------------------------------"));

			document.add(new Paragraph(
					String.format("%-20s : %s", "Current Status", incident.getStatus().getStatusName()), normalFont));

			document.add(new Paragraph(" "));

			// ===========================
			// FOOTER
			// ===========================

			document.add(new Paragraph("=============================================================="));

			Paragraph footer = new Paragraph("Generated by Crime Management System", normalFont);

			footer.setAlignment(Paragraph.ALIGN_CENTER);

			document.add(footer);

			document.close();
			
			logger.info("PDF generated successfully.");

			return new ByteArrayInputStream(out.toByteArray());

		} catch (Exception e) {

			throw new RuntimeException("Error generating PDF");

		}

	}
}