spring.application.name=CMSBackEnd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/cms_backend_db
spring.datasource.username= root
spring.datasource.password= Root@1234
springdoc.api-docs.version=OPENAPI_3_0

logging.level.root=INFO
logging.level.com.hexaware.cms.backend=DEBUG

logging.file.name=logs/cms.log
file.upload-dir=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=lilycandace24@gmail.com
spring.mail.password=drbmhpjeftxbejog

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true